export const FETCH_GAMES_BEGIN = 'FETCH_GAMES_BEGIN';
export const FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS';
export const FETCH_GAMES_FAILURE = 'FETCH_GAMES_FAILURE';
export const SELECT_GAME = 'SELECT_GAME';
export const RECEIVE_GAME = 'RECEIVE_GAME';
export const RETRIEVE_GAMES = 'RETRIEVE_GAMES';
export const ADD_GAME = 'ADD_GAME';
export const REMOVE_GAME = 'REMOVE_GAME';

// export const SELECT_FAVORITE = 'SELECT_FAVORITE';
